name: Package Built by devenv
on:
  schedule:
    - cron: '21 18 * * 5'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-20.04, macos-latest]
        fail-fast: false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Scotch - tarball build
      run: |
        working_flavor=scotch-tarball
        source ${GITHUB_WORKSPACE}/scripts/init
        devenv add ${working_flavor}
        devenv use ${working_flavor}
        devenv show
        devenv build scotch
    - name: Scotch - git repository
      run: |
        working_flavor=scotch-syncgit
        source ${GITHUB_WORKSPACE}/scripts/init
        devenv add ${working_flavor}
        devenv use ${working_flavor}
        devenv show
        SYNCGIT="yes" devenv build scotch
